### ISSUE TITLE
install in linux?

### ISSUE THREAD

**Issue by mafiakb** [PassiveModding/RainbowBOT#1]
how install in linux centos?

**Comment by PassiveModding** [comment]
it is currently windows only as the release is an exe and it is built on .net framework
I may work on converting to .net core at some point but i have little to no linux or net core experience

**Comment by Lyroo** [comment]
hey the guy said theres no bugs so dont worry

**Comment by RealBlazeIt** [comment]
net framework is for pussies switch to core

**Comment by VapidSlay** [comment]
![](https://media.discordapp.net/attachments/336364720099557376/343229428786266112/unknown.png)

**Comment by PassiveModding** [comment]
kids dont know the difference between a bug and a framework
